name: build
on:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  ros_build:
      strategy:
        fail-fast: false
        matrix:
          checks: [
            { ROS_VERSION: "ros2", ROS_DISTRO: "humble", UBUNTU_DISTRO: "22.04", PACKAGES: "
            free_fleet_server_ros2"},
            { ROS_VERSION: "ros1", ROS_DISTRO: "noetic", UBUNTU_DISTRO: "20.04", PACKAGES: "
            ff_rviz_plugins_ros1
            free_fleet_client_ros1" },
          ]
      name: ${{matrix.checks.ROS_VERSION}}_build
      runs-on: ubuntu-${{matrix.checks.UBUNTU_DISTRO}}
      steps:
        - name: pwd
          run: pwd
        - name: deps
          uses: ros-tooling/setup-ros@v0.4
          with:
            required-ros-distributions: ${{matrix.checks.ROS_DISTRO}}
        - name: build
          uses: ros-tooling/action-ros-ci@v0.2
          with:
            target-${{matrix.checks.ROS_VERSION}}-distro: ${{matrix.checks.ROS_DISTRO}}
            # build all packages listed in the meta package
            package-name: |
              free_fleet
              ff_examples_${{matrix.checks.ROS_VERSION}}
              ${{matrix.checks.PACKAGES}}
            vcs-repo-file-url: |
              https://raw.githubusercontent.com/open-rmf/free_fleet/main/ff_${{matrix.checks.ROS_VERSION}}.repos

